-- 025: Mint-grade Bills intelligence.
-- Adds recurring-series inference, durable bill occurrences, paid matching,
-- reminder preferences/events, and user overrides over derived bills.

CREATE TABLE recurring_series (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  series_key TEXT NOT NULL,
  direction TEXT NOT NULL,
  merchant_key TEXT NOT NULL,
  display_name TEXT NOT NULL,
  frequency TEXT NOT NULL,
  interval_days INTEGER NOT NULL,
  typical_amount_cents INTEGER NOT NULL,
  amount_variance_bps INTEGER NOT NULL DEFAULT 0,
  occurrence_count INTEGER NOT NULL DEFAULT 0,
  last_amount_cents INTEGER,
  last_seen_date TEXT,
  next_expected_date TEXT,
  account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'detected',
  source_provider TEXT,
  source_external_id TEXT,
  confidence_bps INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (user_id, series_key)
);
CREATE INDEX idx_recurring_series_user_next
  ON recurring_series(user_id, active, next_expected_date);
CREATE INDEX idx_recurring_series_merchant
  ON recurring_series(user_id, account_id, merchant_key, direction);

ALTER TABLE bills ADD COLUMN recurring_series_id TEXT REFERENCES recurring_series(id) ON DELETE SET NULL;
ALTER TABLE bills ADD COLUMN user_overridden INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX idx_bills_recurring_series
  ON bills(recurring_series_id)
  WHERE recurring_series_id IS NOT NULL;

CREATE TABLE bill_occurrences (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bill_id TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  due_date TEXT NOT NULL,
  expected_amount_cents INTEGER NOT NULL,
  actual_amount_cents INTEGER,
  status TEXT NOT NULL DEFAULT 'upcoming',
  paid_transaction_id TEXT REFERENCES transactions(id) ON DELETE SET NULL,
  paid_evidence TEXT,
  matched_at TEXT,
  source TEXT NOT NULL,
  source_confidence TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (bill_id, due_date)
);
CREATE INDEX idx_bill_occurrences_user_due
  ON bill_occurrences(user_id, status, due_date);
CREATE INDEX idx_bill_occurrences_paid_txn
  ON bill_occurrences(paid_transaction_id)
  WHERE paid_transaction_id IS NOT NULL;

ALTER TABLE user_settings ADD COLUMN bill_reminders_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_settings ADD COLUMN bill_reminder_days TEXT NOT NULL DEFAULT '[7,3,1,0]';

CREATE TABLE notification_events (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bill_occurrence_id TEXT REFERENCES bill_occurrences(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  dedupe_key TEXT NOT NULL,
  scheduled_for TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  delivered_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (user_id, dedupe_key)
);
CREATE INDEX idx_notification_events_pending
  ON notification_events(user_id, status, scheduled_for);

-- Materialize the currently-known obligation for every active bill. Future
-- occurrences are generated by the Bills intelligence service.
INSERT INTO bill_occurrences (
  id, user_id, bill_id, due_date, expected_amount_cents, actual_amount_cents,
  status, paid_transaction_id, paid_evidence, matched_at,
  source, source_confidence, created_at, updated_at
)
SELECT
  'bill-occ:' || b.id || ':' || b.next_due_date,
  b.user_id,
  b.id,
  b.next_due_date,
  b.amount_cents,
  NULL,
  CASE WHEN b.next_due_date < date('now') THEN 'overdue' ELSE 'upcoming' END,
  NULL,
  NULL,
  NULL,
  b.source,
  b.source_confidence,
  b.created_at,
  b.updated_at
FROM bills b
WHERE b.active = 1
  AND b.next_due_date IS NOT NULL
ON CONFLICT(bill_id, due_date) DO NOTHING;
